### ISSUE TITLE
index-list 索引列表滚动 数据不及时

### ISSUE THREAD

**Issue by xuergo** [umicro/uView#883]
![CE8AA5745E009F752B47982F3FDFA479](https://user-images.githubusercontent.com/46159623/113239211-df322d00-92dc-11eb-9e11-8732fe3f6ba2.png)

**Comment by GlantQ** [comment]
我也遇到了同样问题，请问有解决方案吗

**Comment by xuergo** [comment]
> 我也遇到了同样问题，请问有解决方案吗

换组件了

**Comment by GlantQ** [comment]
可以推荐下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月23日(星期五) 上午9:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YanxinNet/uView] index-list 索引列表滚动 数据不及时 (#883)





  
我也遇到了同样问题，请问有解决方案吗
  
换组件了

**Comment by xuergo** [comment]
> 可以推荐下吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月23日(星期五) 上午9:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [YanxinNet/uView] index-list 索引列表滚动 数据不及时 (#883) 我也遇到了同样问题，请问有解决方案吗 换组件了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

https://ext.dcloud.net.cn/plugin?id=4395 这个不能吸顶 官方也是这个做法 靠锚点

**Comment by GlantQ** [comment]
谢谢，我去看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月23日(星期五) 上午9:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YanxinNet/uView] index-list 索引列表滚动 数据不及时 (#883)





  
可以推荐下吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年4月23日(星期五) 上午9:39 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [YanxinNet/uView] index-list 索引列表滚动 数据不及时 (#883) 我也遇到了同样问题，请问有解决方案吗 换组件了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
https://ext.dcloud.net.cn/plugin?id=4395 这个不能吸顶 官方也是这个做法 靠锚点
